services:
  # default configuration for services in *this* file
  _defaults:
    public: false       # Allows optimizing the container by removing unused services; this also means
    # fetching services directly from the container via $container->get() won't work.
    # The best practice is to be explicit about your dependencies anyway.
  Krak\ApiPlatformExtra\Serializer\ConstructorResourceItemNormalizer:
  Krak\ApiPlatformExtra\Serializer\JsonLdConstructorResourceItemNormalizer:
  Krak\ApiPlatformExtra\Operation\PluralDataPathSegmentNameGenerator:
    decorates: api_platform.path_segment_name_generator
    arguments: ['@Krak\ApiPlatformExtra\Operation\PluralDataPathSegmentNameGenerator.inner']
  Krak\ApiPlatformExtra\Metadata\Resource\SchemaOnlyResourceMetadataFactory:
    decorates: api_platform.metadata.resource.metadata_factory
    arguments: ['@Krak\ApiPlatformExtra\Metadata\Resource\SchemaOnlyResourceMetadataFactory.inner']
